[package]
authors = ["James Woodward <james@matoch.com>"]
name = "ldap-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
ldap3 = "0.10.2"
tokio = { version = "1.17.0", features = ["full"] }
warp = "0.3"
chrono = "0.4.19"
convert_case = "0.5.0"
